### ISSUE TITLE
Incorrect sunrise time calculation for Beijing timezone causes infinite loop

### ISSUE THREAD

**Issue by GlekoMa** [lhecker/windows-dark-mode-switcher#6]
**Description**

First of all, thank you for creating this tool! I really appreciate how lightweight and useful it is.

While using it, I found a bug in the `suncourse_is_daytime` function when calculating sunrise/sunset times for Beijing coordinates (lat: 39.906217, lon: 116.3912757).

The issue occurs because:
1. `noaa_sunset_sunrise()` returns a negative sunrise time (-0.646420)
2. This negative value causes `minutes` to be negative when converted
3. `next.wMinute = (WORD)lround(minutes);` becomes an invalid value (65497)
4. `SystemTimeToFileTime()` fails silently due to invalid minute value
5. This causes `next_ft.QuadPart` to remain 0
6. The condition `(next_ft.QuadPart < now_ft.QuadPart)` is always true
7. Results in an infinite loop and high CPU usage

The sunrise time -0.646420 returned by `noaa_sunset_sunrise()` is actually correct according to [Paul Schlyter's algorithm](https://stjarnhimlen.se/comp/sunriset.c). It means the sunrise occurs at UTC 23:21 (24 - 0.646420) of the previous day.

**Steps to reproduce**

Edit function `suncourse_is_daytime` of `src\suncourse.c` to this:

```c
bool suncourse_is_daytime(float lat, float lon, FILETIME_QUAD* next_update)
{
    //SYSTEMTIME now;
    //GetSystemTime(&now);
    //
    // --- Beijing  (UTC+8) ---
    lat = 39.906217, lon = 116.3912757;
    SYSTEMTIME now = { 2024, 12, 4, 5, 12, 0, 0, 0};

    FILETIME_QUAD now_ft = {};
    SystemTimeToFileTime(&now, &now_ft.FtPart);
    ...
}
```

Compile and run, and observe the CPU usage of the program.

**Possible solution**

Maybe need to properly handle negative hours by adding 24 to normalize them to [0, 24) range. However, as I'm not familiar with the algorithm, there might be better approaches to handle this edge case.

**Comment by lhecker** [comment]
Thank you so much for this excellent issue description! I'll look into this as soon as I can.

**Comment by lhecker** [comment]
From what I can tell, your suggestion to simply add +24 before calculating the modulo was spot on. I've published https://github.com/lhecker/windows-dark-mode-switcher/releases/tag/v0.1.2 with a fix. Thanks!

**Comment by lhecker** [comment]
I have bad news: The fix was not quite complete. The `next_h` value is converted to hours and minutes, but because the conversion happens independent of each other, the minute portion may be rounded to 60, which is an invalid value. This causes the conversion to _also_ fail and results in an infinite loop.

https://github.com/lhecker/windows-dark-mode-switcher/blob/d2c8f3134915e9583d3fbc6ae2791a51c5754f95/src/suncourse.c#L72-L77

I published https://github.com/lhecker/windows-dark-mode-switcher/releases/tag/v0.1.3 which fixes the issue.
